name: BOT SAHAM 🤖

on:
  schedule:
  - cron: '0 2-9 * * 1-5'
    
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - name: Tarik Kode
      uses: actions/checkout@v3
      
    - name: Siapin Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install pip
      run: pip install yfinance pandas numpy holidays aiohttp
      
    - name: JALANKAN BOT SAHAM
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: python bot_saham.py
